[program:cariq-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/cariq/backend/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=cariq
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/cariq/worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stopwaitsecs=3600
